# Generated by Django 4.0.3 on 2022-04-04 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=60)),
                ('act', models.PositiveIntegerField(choices=[(1, 'Rogue Encampment'), (2, 'Lut Gholein'), (3, 'Kurast Docks'), (4, 'Pandemonium Fortress'), (5, 'Harrogath')])),
                ('normal_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(43)])),
                ('nightmare_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(36), django.core.validators.MaxValueValidator(66)])),
                ('hell_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(67), django.core.validators.MaxValueValidator(87)])),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
