# Generated by Django 4.0.3 on 2022-04-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_alter_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='has_waypoint',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
