# Generated by Django 4.0.3 on 2022-04-08 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_area_has_waypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='hell_level',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(67), django.core.validators.MaxValueValidator(87)]),
        ),
        migrations.AlterField(
            model_name='area',
            name='nightmare_level',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(36), django.core.validators.MaxValueValidator(66)]),
        ),
        migrations.AlterField(
            model_name='area',
            name='normal_level',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(43)]),
        ),
    ]
