# Generated by Django 4.0.3 on 2022-04-04 09:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('char_class', models.CharField(choices=[('amazon', 'Amazon'), ('barbarian', 'Barbarian'), ('necromancer', 'Necromancer'), ('paladin', 'Paladin'), ('sorceress', 'Sorceress'), ('druid', 'Druid'), ('assassin', 'Assassin')], max_length=11)),
                ('expansion', models.BooleanField(blank=True, default=True)),
                ('hardcore', models.BooleanField(blank=True, default=False)),
                ('ladder', models.BooleanField(blank=True, default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
