# Generated by Django 4.0.3 on 2022-04-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_runeword_level_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runeword',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
