# Generated by Django 4.0.3 on 2022-04-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_runeword_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='level_type',
            field=models.CharField(choices=[('normal', 'normal'), ('exceptional', 'exceptional'), ('elite', 'elite')], default='elite', max_length=11),
            preserve_default=False,
        ),
    ]
