# Generated by Django 4.0.3 on 2022-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_runeinruneword_rune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('armor', 'Armor'), ('belt', 'Belt'), ('boots', 'Boots'), ('gloves', 'Gloves'), ('helmet', 'Helmet'), ('barb_helm', "Barbarian's Helm"), ('druid_pelt', "Druid's Pelt"), ('shield', 'Shield'), ('auric_shield', "Paladin's Shield"), ('shrunken_head', "Necromancer's Shrunken Head"), ('axe_1h', 'One-handed Axe'), ('axe_2h', 'Two-handed Axe'), ('katar', "Assassin's Claw"), ('dagger', 'Dagger'), ('sword_1h', 'One-handed Sword'), ('sword_2h', 'Two-handed Sword'), ('hammer', 'Hammer'), ('maul', 'Maul'), ('mace', 'Mace'), ('club', 'Club'), ('scepter', 'Scepter'), ('polearm', 'Polearm'), ('amazon_spear', "Amazon's Spear"), ('spear', 'Spear'), ('wand', 'Wand'), ('staff', 'Staff'), ('orb', "Sorceress' Orb"), ('crossbow', 'Crossbow'), ('amazon_bow', "Amazon's Bow"), ('bow', 'Bow'), ('throwing', 'Throwing'), ('amazon_javelin', "Amazon's Javelin"), ('javelin', 'Javelin'), ('ring', 'Ring'), ('amulet', 'Amulet'), ('gem', 'Gem'), ('rune', 'Rune'), ('charm', 'Charm'), ('jewel', 'Jewel'), ('scroll', 'Scroll'), ('tome', 'Tome'), ('ammo', 'Ammunition'), ('potion', 'Potion'), ('key', 'Key'), ('quest', 'Quest')], max_length=14),
        ),
        migrations.AlterField(
            model_name='itembase',
            name='type',
            field=models.CharField(choices=[('armor', 'Armor'), ('belt', 'Belt'), ('boots', 'Boots'), ('gloves', 'Gloves'), ('helmet', 'Helmet'), ('barb_helm', "Barbarian's Helm"), ('druid_pelt', "Druid's Pelt"), ('shield', 'Shield'), ('auric_shield', "Paladin's Shield"), ('shrunken_head', "Necromancer's Shrunken Head"), ('axe_1h', 'One-handed Axe'), ('axe_2h', 'Two-handed Axe'), ('katar', "Assassin's Claw"), ('dagger', 'Dagger'), ('sword_1h', 'One-handed Sword'), ('sword_2h', 'Two-handed Sword'), ('hammer', 'Hammer'), ('maul', 'Maul'), ('mace', 'Mace'), ('club', 'Club'), ('scepter', 'Scepter'), ('polearm', 'Polearm'), ('amazon_spear', "Amazon's Spear"), ('spear', 'Spear'), ('wand', 'Wand'), ('staff', 'Staff'), ('orb', "Sorceress' Orb"), ('crossbow', 'Crossbow'), ('amazon_bow', "Amazon's Bow"), ('bow', 'Bow'), ('throwing', 'Throwing'), ('amazon_javelin', "Amazon's Javelin"), ('javelin', 'Javelin'), ('ring', 'Ring'), ('amulet', 'Amulet'), ('gem', 'Gem'), ('rune', 'Rune'), ('charm', 'Charm'), ('jewel', 'Jewel'), ('scroll', 'Scroll'), ('tome', 'Tome'), ('ammo', 'Ammunition'), ('potion', 'Potion'), ('key', 'Key'), ('quest', 'Quest')], max_length=14),
        ),
    ]
