# Generated by Django 4.0.3 on 2022-04-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_setitem_alter_concreteitem_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueItem',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Unique items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.concreteitem',),
        ),
    ]
